In [74]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_csv('Data Sets//cars.csv')
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [76]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [77]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [78]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# One-Hot Encoding using Pandas

In [79]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# K-1 encoding

In [80]:
pd.get_dummies(df,columns=['fuel','owner'], drop_first= True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

Problem : pandas can't remember exact order of new cols

Solution : use OneHotEncoder from sklearn

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [82]:
# Train Test Split
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns= 'selling_price'), df['selling_price'],test_size=0.3, random_state=0)

In [87]:
ohe = OneHotEncoder(drop= 'first', sparse_output= False, dtype= 'int32') # drop= 'first' -> solve multicollinearity

In [88]:
x_train_new = ohe.fit_transform(x_train[['fuel', 'owner']])

In [89]:
x_test_new = ohe.fit_transform(x_test[['fuel', 'owner']])

In [90]:
# joining new ones : 
np.hstack((x_train[['brand','km_driven']],x_train_new))

array([['Tata', 20000, 0, ..., 0, 0, 0],
       ['Maruti', 30000, 0, ..., 0, 0, 0],
       ['Maruti', 15000, 0, ..., 0, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]],
      shape=(5689, 9), dtype=object)

# One-Hot Encoding TOP VALUES

threshold -> 100 cars per brand

In [92]:
counts = df['brand'].value_counts()
threshold = 100

In [99]:
others = counts[counts < 100].index

Problem : 36 rows below :

In [102]:
pd.get_dummies(df, columns= ['brand'])

,km_driven,fuel,owner,selling_price,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,...,brand_Mitsubishi,brand_Nissan,brand_Opel,brand_Peugeot,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,145500,Diesel,First Owner,450000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,120000,Diesel,Second Owner,370000,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,140000,Petrol,Third Owner,158000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,127000,Diesel,First Owner,225000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,120000,Petrol,First Owner,130000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,110000,Petrol,First Owner,320000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8124,119000,Diesel,Fourth & Above Owner,135000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8125,120000,Diesel,First Owner,382000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8126,25000,Diesel,First Owner,290000,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
8127,25000,Diesel,First Owner,290000,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

Solution :

In [106]:
encoded_df = pd.get_dummies(df['brand'].replace(others, "Others")).astype('Int32')

In [109]:
encoded_df.sample(10)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Others,Renault,Skoda,Tata,Toyota,Volkswagen
4894,0,0,0,0,0,1,0,0,0,0,0,0,0
2440,0,0,0,0,1,0,0,0,0,0,0,0,0
7724,0,0,0,0,0,0,1,0,0,0,0,0,0
1089,0,0,0,0,0,0,1,0,0,0,0,0,0
2652,0,0,0,0,0,0,1,0,0,0,0,0,0
7159,0,0,0,0,0,0,0,0,1,0,0,0,0
900,0,0,0,0,1,0,0,0,0,0,0,0,0
399,0,0,0,1,0,0,0,0,0,0,0,0,0
402,0,0,0,0,0,0,1,0,0,0,0,0,0
6368,0,0,0,0,0,0,1,0,0,0,0,0,0